### ISSUE TITLE
Paper Backgrounds

### ISSUE THREAD

**Issue by EdKerscher** [ehgoodenough/papercut#31]
Paper Backgrounds

**Comment by EdKerscher** [comment]
![level_background_notepaper1](https://cloud.githubusercontent.com/assets/10680764/10413328/c69eb828-6f59-11e5-9ef7-650594727a85.png)

**Comment by ehgoodenough** [comment]
I want more! :D

**Comment by EdKerscher** [comment]
![level_background_parchmentpaper1](https://cloud.githubusercontent.com/assets/10680764/10414233/4bcc59fa-6f7e-11e5-847a-63106b908770.png)

**Comment by EdKerscher** [comment]
![level_background_officepaper1](https://cloud.githubusercontent.com/assets/10680764/10418689/f6ea4e4e-7016-11e5-9fe3-e94933542c67.png)
![level_background_burntcardstockpaper](https://cloud.githubusercontent.com/assets/10680764/10418690/f6eab258-7016-11e5-9ca3-72abf9ccd225.png)
