### ISSUE TITLE
Boss Art Assets

### ISSUE THREAD

**Issue by eCorbeau** [ehgoodenough/papercut#47]
Lich upper body & head, with beating red heart weak point, and a flippable skeletal hand sprite.

**Comment by EdKerscher** [comment]
![endboss_lich_heart](https://cloud.githubusercontent.com/assets/10680764/10416629/acd3c374-6fd2-11e5-8462-bd808b456945.png)
![Uploading EndBoss_Lich_LeftHand.png…]()
![Uploading EndBoss_Lich_RightHand.png…]()
![Uploading EndBoss_Lich_Shuriken.png…]()
![Uploading UI_EndBossHealth_Full.png…]()
![Uploading UI_EndBossHealth_Half.png…]()
