### ISSUE TITLE
"node build.js" returns error "domain of undefined while parsing" 

### ISSUE THREAD

**Issue by YonasBerhe** [ehgoodenough/papercut#76]
TypeError: Cannot set property 'domain' of undefined while parsing file: /Users/sanoy/code/tuts/papercut/source/scripts/data/Images.js

```
TypeError: Cannot set property 'domain' of undefined while parsing file: /Users/sanoy/code/tuts/papercut/source/scripts/data/Music.js
```

**Comment by ehgoodenough** [comment]
Hey! Thanks for reporting! Could you run `node --version` and tell me what version of node you're running? During the game jam, we learned that only v0.12.x works with our build system. You can install `nvm` to help switch between versions really easily. Tell me if that doesn't work!!

![selfie-1](http://i.imgur.com/xAflvI7.gif)
